// Sources CC-licensed field recordings from Openverse for the story soundscapes,
// and trims each one to a short loop.
//
// The trim is done on MP3 frame boundaries rather than by re-encoding: every
// frame carries its own header, so cutting between two of them leaves a valid
// file. It keeps a 40-second field recording down to a 25-second loop without
// putting a transcoder in the toolchain.
import fs from 'node:fs/promises'
import path from 'node:path'

const OUT = path.resolve('public/sounds')
const DATA = path.resolve('src/data/sounds.generated.ts')
const UA = 'ROZ-prototype/1.0 (editorial demo)'
const SECONDS = 25

// [file name, Openverse audio id]. Three of the four are recorded in India;
// the site interior is not, and the page says so rather than implying it is.
const PICKS = [
  ['before-light', '52f230a2-9048-429e-bc0c-f7ce771e0961'],
  ['the-site',     'f94236d8-ba4c-4890-9385-6402d773ce33'],
  ['the-road',     '4c4db247-83bc-4772-949e-cde1fc95b50d'],
  ['after-dark',   '95888714-8e80-4d68-a1d1-a48d2daa7f6c'],
]

const L3_SAMPLES = { 1: 1152, 2: 576, 2.5: 576 }
const BITRATE = {
  1: [0, 32, 40, 48, 56, 64, 80, 96, 112, 128, 160, 192, 224, 256, 320, 0],
  2: [0, 8, 16, 24, 32, 40, 48, 56, 64, 80, 96, 112, 128, 144, 160, 0],
}
const SAMPLERATE = { 1: [44100, 48000, 32000], 2: [22050, 24000, 16000], 2.5: [11025, 12000, 8000] }

/** Walk the MP3 frame chain and return the byte offset closest to `seconds`. */
function trimOffset(buf, seconds) {
  let at = 0
  // Drop any ID3v2 tag — it is metadata and artwork, and neither is wanted here.
  if (buf.slice(0, 3).toString('latin1') === 'ID3') {
    const size = ((buf[6] & 0x7f) << 21) | ((buf[7] & 0x7f) << 14) | ((buf[8] & 0x7f) << 7) | (buf[9] & 0x7f)
    at = 10 + size
  }
  const start = at
  let played = 0
  while (at + 4 <= buf.length) {
    if (buf[at] !== 0xff || (buf[at + 1] & 0xe0) !== 0xe0) { at++; continue }
    const versionBits = (buf[at + 1] >> 3) & 3
    const layerBits = (buf[at + 1] >> 1) & 3
    if (versionBits === 1 || layerBits !== 1) { at++; continue } // Layer III only
    const version = versionBits === 3 ? 1 : versionBits === 2 ? 2 : 2.5
    const kbps = BITRATE[version === 1 ? 1 : 2][(buf[at + 2] >> 4) & 0xf]
    const rate = SAMPLERATE[version][(buf[at + 2] >> 2) & 3]
    if (!kbps || !rate) { at++; continue }
    const pad = (buf[at + 2] >> 1) & 1
    const len = Math.floor(((version === 1 ? 144000 : 72000) * kbps) / rate) + pad
    if (len < 4) { at++; continue }
    played += L3_SAMPLES[version] / rate
    at += len
    if (played >= seconds) break
  }
  return { start, end: Math.min(at, buf.length), seconds: played }
}

async function lookup(id) {
  const r = await fetch(`https://api.openverse.org/v1/audio/${id}/`, {
    headers: { 'User-Agent': UA },
    signal: AbortSignal.timeout(30000),
  })
  if (!r.ok) throw new Error(`lookup ${id}: ${r.status}`)
  return r.json()
}

await fs.mkdir(OUT, { recursive: true })
const manifest = []

for (const [slug, id] of PICKS) {
  const rec = await lookup(id)
  // `url` is the open CDN preview. The `alt_files` originals sit behind the
  // host's own API key, so they are not reachable from here.
  const src = rec.url
  const r = await fetch(src, { headers: { 'User-Agent': UA }, signal: AbortSignal.timeout(60000) })
  if (!r.ok) throw new Error(`download ${slug}: ${r.status}`)
  const raw = Buffer.from(await r.arrayBuffer())
  const cut = trimOffset(raw, SECONDS)
  const out = raw.subarray(cut.start, cut.end)
  await fs.writeFile(path.join(OUT, `${slug}.mp3`), out)
  manifest.push({
    slug,
    src: `/sounds/${slug}.mp3`,
    seconds: Number(cut.seconds.toFixed(1)),
    bytes: out.length,
    credit: {
      creator: rec.creator ?? 'Unknown',
      license: `${(rec.license ?? '').toUpperCase()} ${rec.license_version ?? ''}`.trim(),
      licenseUrl: rec.license_url,
      source: rec.foreign_landing_url,
      title: rec.title ?? '',
    },
  })
  console.log(`${slug.padEnd(14)} ${cut.seconds.toFixed(1)}s  ${(out.length / 1024).toFixed(0)} kB  ${rec.creator}`)
}

const ts = `// AUTO-GENERATED by tools/fetch-audio.mjs — do not edit by hand.
export type Sound = {
  slug: string
  src: string
  seconds: number
  bytes: number
  credit: { creator: string; license: string; licenseUrl: string; source: string; title: string }
}

export const SOUNDS = ${JSON.stringify(Object.fromEntries(manifest.map((m) => [m.slug, m])), null, 2)} satisfies Record<string, Sound>

export type SoundId = keyof typeof SOUNDS
`
await fs.writeFile(DATA, ts)
console.log('\nwrote', path.relative(process.cwd(), DATA))
