// AUTO-GENERATED by tools/build-images.mjs — do not edit by hand.
export type Frame = {
  id: string
  widths: number[]
  /** width / height */
  aspect: number
  /** inlined 20px WebP, used as the background under the real frame */
  lqip: string
  /** portrait re-crop, served to narrow screens instead of squeezing the wide one */
  mobile: { widths: number[]; aspect: number; lqip: string } | null
  credit: { creator: string; license: string; licenseUrl: string; source: string } | null
}

export const FRAMES = {
  "dawn": {
    "id": "dawn",
    "widths": [
      1280,
      1920
    ],
    "aspect": 1.7778,
    "lqip": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADQAwCdASoUAAsAPxFyslCsJqSisAgBgCIJaACdMoADTaPw10ve96AA/tNHaSR9tb/Nt54OSn6+0zbrgIIyxuYb5YnMeO0PBI6VDp9wAAA=",
    "mobile": {
      "widths": [
        480,
        760,
        1000
      ],
      "aspect": 0.75,
      "lqip": "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAABwBACdASoUABsAPwFwq1ArJyQit/VYAWAgCWYAnTLjgphVRpdso4AyHtzzMAD+6oAMy/iBFF4X+6M3rRpU/Uajm2u4tAXaA2CyzNa7l61GsKVX09FTh7UY1Sa5YtWrTKrsfWa+juoujh09egAAAA=="
    },
    "credit": {
      "creator": "Rakesh JV",
      "license": "BY-NC 2.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-nc/2.0/",
      "source": "https://www.flickr.com/photos/59281136@N04/6765358609"
    }
  },
  "kiln": {
    "id": "kiln",
    "widths": [
      1280,
      1920
    ],
    "aspect": 1.7778,
    "lqip": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAAAQBACdASoUAAsAPxFysFAsJqSisAgBgCIJZgCdMoADTg1aPoBD/fo8AAD+3/S2jxq1WvfFixUMOyV/W3hQExhKWRrHpDw8ZMzFMvyqnMbgCkb6Gt5GtQD7gAA=",
    "mobile": {
      "widths": [
        480,
        760
      ],
      "aspect": 0.75,
      "lqip": "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAADQBACdASoUABsAPxF2slGsJySiqA1RgCIJZAC/OEXfRDJaqXtdpCclOylhdmBEAAD+9gLWBnZ485kwD/2H3+acoDkoC+a5zUke7+RkX3bOxQNBqiBouJIsjeFw/CbA+IDpn4kba8JEEFgOyC1c+qo+RXzwAA=="
    },
    "credit": {
      "creator": "rahuldlucca",
      "license": "BY 2.0",
      "licenseUrl": "https://creativecommons.org/licenses/by/2.0/",
      "source": "https://www.flickr.com/photos/8213176@N03/2245305563"
    }
  },
  "chai": {
    "id": "chai",
    "widths": [
      1280,
      1920
    ],
    "aspect": 1.7778,
    "lqip": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAAAQBACdASoUAAsAPxF0tFEsJqUisAgBgCIJYwCAAAcOnMrG3swhp/4kAAD+6YTeZxajNczAV10Y47GrJ2nj8/LhHCuMh0CFW2FgqEKoAAA=",
    "mobile": {
      "widths": [
        480,
        760,
        1000
      ],
      "aspect": 0.75,
      "lqip": "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAAAwBQCdASoUABsAPxF0sFAsJySisAgBgCIJYgDImCFU2QZNh9idkFSypG7Zsi1+ddjgAAD+8MuwsPIHjlJFV0x8sdBL5sx4KI4GT8AfuT8wSi/BSVKvHbVvVvk05M4jnNH83tQtn3Zy83DIL6PLg6w0/kaadgAA"
    },
    "credit": {
      "creator": "Scalino",
      "license": "BY-NC 2.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-nc/2.0/",
      "source": "https://www.flickr.com/photos/45697441@N00/7741702782"
    }
  },
  "raju": {
    "id": "raju",
    "widths": [
      900,
      1400,
      1800
    ],
    "aspect": 1.5,
    "lqip": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAABQBACdASoUAA0APxFysFCsJqSisAgBgCIJZgCdMoRwACUEvOq8RYJdhqQAAP6rmkeUB38icxlkazWB1lYSMbZKDOQ+asXesn8D7b7U2soNfHGaWyf3rXM2At5WDooeAAA=",
    "mobile": {
      "widths": [
        480,
        760,
        1000
      ],
      "aspect": 0.75,
      "lqip": "data:image/webp;base64,UklGRp4AAABXRUJQVlA4IJIAAACQBQCdASoUABsAPxFysFCsJqSisAgBgCIJYgCdMoLT9AlOXN3xi2rR4ouWH/2sXQUuDTWyoAD+dIO//NI+ZlHMKLXPZ42RmELhDFVnOykPtL9heSCe4x3hb540SD+/eN7Gll4kKb7+SG3BID/ek8v/pMaUY8kptovp+Pptrk9QxiuwQTpsg4ZYgSS07k3fcMAAAA=="
    },
    "credit": {
      "creator": "Shubhodeep Roy / IAPB",
      "license": "BY-NC-SA 2.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-nc-sa/2.0/",
      "source": "https://www.flickr.com/photos/89097492@N06/51542875888"
    }
  },
  "shanti": {
    "id": "shanti",
    "widths": [
      600,
      900
    ],
    "aspect": 0.8,
    "lqip": "data:image/webp;base64,UklGRqAAAABXRUJQVlA4IJQAAABQBQCdASoUABkAPxF2s1GsJySiqA1RgCIJYwC2yA3ylmJOGKXKSR12Ue3U5iMpmvl8swAA9r1F2xFjllMV04Z85I/FwA0LzyR8eYhKImP3Xd0rDj1dOLF0l5arWJXreVALyMACCa3xBHSnhVE/cm9nGhwuB+5isrbU2v3FRPOl6r0dC9QP83QBSgvz+duwWe5I/gAA",
    "mobile": null,
    "credit": {
      "creator": "Shreyans Bhansali",
      "license": "BY-NC-SA 2.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-nc-sa/2.0/",
      "source": "https://www.flickr.com/photos/94416001@N00/4168417896"
    }
  },
  "imran": {
    "id": "imran",
    "widths": [
      900,
      1400,
      1800
    ],
    "aspect": 1.5,
    "lqip": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAAAwBACdASoUAA0APxFysVCsJqSisAgBgCIJZQCdMoAC/D2RwZuxdKdopQAA+pwDHSDw0AUZVo+IO7VYaUTs24qbVw/p1mVx6TZnicLgsAA=",
    "mobile": {
      "widths": [
        480,
        760,
        1000
      ],
      "aspect": 0.75,
      "lqip": "data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAAAwBQCdASoUABsAPxGCuVWsKKWjKAgBgCIJYwDCgBEStsOYeSs1HJCmz5YewhJMP2lwAAD80Ib+kmavdJLN/qKpA7QG8qQFSanG7ncOHOm0hHf8+aipD3K9FziWzQaP56cS77cdL8NwDhS0hsx99BUtBYLhvMCv7CwEAA=="
    },
    "credit": {
      "creator": "diametrik",
      "license": "BY 2.0",
      "licenseUrl": "https://creativecommons.org/licenses/by/2.0/",
      "source": "https://www.flickr.com/photos/58435577@N00/354965078"
    }
  },
  "meena": {
    "id": "meena",
    "widths": [
      600,
      900,
      1200,
      1500
    ],
    "aspect": 0.8,
    "lqip": "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAACwBACdASoUABkAPxF0sFAsJySisAgBgCIJZAC7AB6VYB/n5JZDm7deQKAjxhAAAP7ZWFBIoFghSqB/jwkaIgDHvfqOx78H2qd2H/sIW5NkwIvv0Ptyipv2oCeM0H3xaMkJTqvmbR3c+QqxAgdihAHQAAA=",
    "mobile": null,
    "credit": {
      "creator": "Jorge Royan",
      "license": "BY-SA 3.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
      "source": "https://commons.wikimedia.org/w/index.php?curid=19741911"
    }
  },
  "ramesh": {
    "id": "ramesh",
    "widths": [
      600,
      900,
      1200
    ],
    "aspect": 0.8,
    "lqip": "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAACwBACdASoUABkAPxF6sFMsJ6QiqA1RgCIJZwAAI94GUy8iq2dh73lUhKzIAQIAAP6hRFhBFXm4afb48bRHDwx+LiNPpKvzZGgJv52nUhg3pguXHmuG8VMiUcpkQGOpbwj7RrwfZm2pIsvuCFFFDimeXZLY8GuEou6aEkx0AAAAAA==",
    "mobile": null,
    "credit": {
      "creator": "Mr Moss",
      "license": "BY 2.0",
      "licenseUrl": "https://creativecommons.org/licenses/by/2.0/",
      "source": "https://www.flickr.com/photos/49734171@N00/17179182421"
    }
  },
  "asha": {
    "id": "asha",
    "widths": [
      900,
      1400,
      1800
    ],
    "aspect": 1.85,
    "lqip": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAACwAwCdASoUAAsAPxF0sVAsJySisAgBgCIJZwAAPD9nly7gbNYsAAD+wVjrXOWwcOR447pg2QyjYV8vgTSgpKXGqLCX2hQAAAA=",
    "mobile": {
      "widths": [
        480,
        760,
        1000
      ],
      "aspect": 0.75,
      "lqip": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAADQBACdASoUABsAPxF6tFMsJ6UiqAqpgCIJZwDNAoABUeiVyQCuUpPsHrhpFS5AAAD+Ri0kfZlgGcza5/tiJXBpWL9C7182r3LZNJbQeKmy8k4KyqzAkTLadUpXmvfUzBavxbAA"
    },
    "credit": {
      "creator": "mynameisharsha",
      "license": "BY-SA 2.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0/",
      "source": "https://www.flickr.com/photos/27526538@N07/2897131649"
    }
  },
  "arjun": {
    "id": "arjun",
    "widths": [
      900,
      1400,
      1800
    ],
    "aspect": 1.5,
    "lqip": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAACQAwCdASoUAA0APxF0sVCsJqSisAgBgCIJZQC06B5uqbzxVn6AANyAmRNfmRSeoYrAQUeyH7C/hpslQ9tN9+peVCtYdqfAAAA=",
    "mobile": {
      "widths": [
        480,
        760,
        1000
      ],
      "aspect": 0.75,
      "lqip": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAAAQBQCdASoUABsAPv1qqlArJiQit/qoAWAfiWUAuwAj0CXic3SYL7gLWF1FqsR4VQIAAPegvsmKVwtfQxqqI7sxm5czVLo3REcRe0MOi904Ov8f45l62w8ySQh6fkoeAAA="
    },
    "credit": {
      "creator": "Faisal Akram Ether",
      "license": "BY-SA 2.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0/",
      "source": "https://www.flickr.com/photos/72847119@N00/5662363322"
    }
  },
  "mist": {
    "id": "mist",
    "widths": [
      720,
      1100
    ],
    "aspect": 1.5,
    "lqip": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAACwAwCdASoUAA0APxF0tFEsJqUisAgBgCIJZwCw7CHcahc0gvQqAAD9ySv8dsvGrmcfvOkqE1q4/WAA",
    "mobile": null,
    "credit": {
      "creator": "Eric.Parker",
      "license": "BY-NC 2.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-nc/2.0/",
      "source": "https://www.flickr.com/photos/13484951@N00/9096278476"
    }
  },
  "scaffold": {
    "id": "scaffold",
    "widths": [
      720,
      1100
    ],
    "aspect": 1.5,
    "lqip": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADwAwCdASoUAA0APxFysFAsJqSisAgBgCIJQBOmUABWHGhf46WhpjJAAPpuR/eu0dFkCIF3QVrWoYCv2OJ62o+igQ9u57wqRYrXfAAA",
    "mobile": null,
    "credit": {
      "creator": "VnGrijl",
      "license": "BY 2.0",
      "licenseUrl": "https://creativecommons.org/licenses/by/2.0/",
      "source": "https://www.flickr.com/photos/22406652@N02/8474433074"
    }
  },
  "inside-auto": {
    "id": "inside-auto",
    "widths": [
      720,
      1100
    ],
    "aspect": 1.5,
    "lqip": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAADwAwCdASoUAA0APxFwsFAsJiSisAgBgCIJaACdMoADSYvHdmKV6lAgAP5FRwo3LTl06JQbc52mm9an5oHPcYe9+uftoKskdFvmXjdkbKHqItTYX2pdHwHgFJCGdhVGiAA=",
    "mobile": null,
    "credit": {
      "creator": "abrinsky",
      "license": "BY-NC-SA 2.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-nc-sa/2.0/",
      "source": "https://www.flickr.com/photos/12176100@N00/431422814"
    }
  },
  "machine": {
    "id": "machine",
    "widths": [
      720,
      1100
    ],
    "aspect": 1.5,
    "lqip": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAADQAwCdASoUAA0APxFwsFAsJiSisAgBgCIJYwC06CBhA+E56pyrLQAA/fXkYjShL7j0JQTA6nLM8oi82M5RlD+60XdKZVJktwu405AyApOnF9R3PXya9U4AAAA=",
    "mobile": null,
    "credit": {
      "creator": "OXLAEY.com",
      "license": "BY 2.0",
      "licenseUrl": "https://creativecommons.org/licenses/by/2.0/",
      "source": "https://www.flickr.com/photos/97185651@N08/15343920184"
    }
  },
  "wet-road": {
    "id": "wet-road",
    "widths": [
      720,
      1100
    ],
    "aspect": 1.5,
    "lqip": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAABQAwCdASoUAA0APxFysFAsJqSisAgBgCIJaQAAUqt08wigAAD+8N9wdkw6h7fGfyicgOEgdcBqr2Jgb2zzvqEAAAA=",
    "mobile": null,
    "credit": {
      "creator": "VinothChandar",
      "license": "BY 2.0",
      "licenseUrl": "https://creativecommons.org/licenses/by/2.0/",
      "source": "https://www.flickr.com/photos/44345361@N06/8115638610"
    }
  },
  "ghat": {
    "id": "ghat",
    "widths": [
      720,
      1100,
      1440
    ],
    "aspect": 1.5,
    "lqip": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAACwAwCdASoUAA0APxF0tFEsJqUisAgBgCIJQA7gAIsMp1JXXI+UgAD+x9nX/Rzm94p+wCbKBXcXs6/6/d/f0vaaKdDNlH6faf/i7Zp8GPooqrv4BgA=",
    "mobile": null,
    "credit": {
      "creator": "evoo73",
      "license": "BY 2.0",
      "licenseUrl": "https://creativecommons.org/licenses/by/2.0/",
      "source": "https://www.flickr.com/photos/21761329@N03/16109392338"
    }
  },
  "rj-open": {
    "id": "rj-open",
    "widths": [
      1280,
      1920
    ],
    "aspect": 1.7778,
    "lqip": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAABQBACdASoUAAsAPxF0sVCsJqSisAgBgCIJZgCdMoRwACUMzeLHTQMaVHqAAP6rmkeUJAgh13H2ZEMUr6VMCOBDUDzLskj6O7nClgbdKriyWLj3fczp3sr33Ol/IyoAAAA=",
    "mobile": {
      "widths": [
        480,
        760,
        1000
      ],
      "aspect": 0.75,
      "lqip": "data:image/webp;base64,UklGRp4AAABXRUJQVlA4IJIAAACQBQCdASoUABsAPxFysFCsJqSisAgBgCIJYgCdMoLT9AlOXN3xi2rR4ouWH/2sXQUuDTWyoAD+dIO//NI+ZlHMKLXPZ42RmELhDFVnOykPtL9heSCe4x3hb540SD+/eN7Gll4kKb7+SG3BID/ek8v/pMaUY8kptovp+Pptrk9QxiuwQTpsg4ZYgSS07k3fcMAAAA=="
    },
    "credit": {
      "creator": "IAPB/VISION 2020",
      "license": "BY-NC-SA 2.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-nc-sa/2.0/",
      "source": "https://www.flickr.com/photos/89097492@N06/51542875888"
    }
  },
  "rj-h1": {
    "id": "rj-h1",
    "widths": [
      1280,
      1920
    ],
    "aspect": 1.85,
    "lqip": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAABwAwCdASoUAAsAPxFysFAsJqSisAgBgCIJYgCdABjoBH953AAA/u9IgTUBerkzvCDv07m1rgg9b2tp4oz8oTf8dtVb25vgAAA=",
    "mobile": {
      "widths": [
        480,
        760,
        1000
      ],
      "aspect": 0.75,
      "lqip": "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAABQBQCdASoUABsAPxFwsVAsJiSisBgMAYAiCWYAnTLjfgAVI+8x7w3AJ0eCr7h23SIClAAA/u6XUMvPkxSCDROF+4KXq7b2+N39odfljJ+fV14WsL88ETohHklYlUdkXwelam8sNxZxKRhE1y55FKwNt2QQAA=="
    },
    "credit": {
      "creator": "Eric.Parker",
      "license": "BY-NC 2.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-nc/2.0/",
      "source": "https://www.flickr.com/photos/13484951@N00/9094047071"
    }
  },
  "rj-h2": {
    "id": "rj-h2",
    "widths": [
      1280,
      1920
    ],
    "aspect": 1.85,
    "lqip": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAACQAwCdASoUAAsAPxFysVAsJqSisAgBgCIJYgCdACHYf6xCDCSwAP7Dl/FKw/K0191cCAzDTJhDcg1HwGUsJTOfkR8PXe8tm7HLscFAAAA=",
    "mobile": {
      "widths": [
        480,
        760,
        1000
      ],
      "aspect": 0.75,
      "lqip": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAABwBACdASoUABsAPxF0s1MsJiSisBgIAYAiCWMAAI+Nteld022yo2bodDvOoAD+6o/kXzr5D/zwTLbS0vZ6U2sj9N5Jh8LlZukl3ktjiXggOtiG5ptftMiDW9ZbxjZ+yIOLAAAA"
    },
    "credit": {
      "creator": "Well-Bred Kannan (WBK Photography)",
      "license": "BY-NC-ND 2.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-nc-nd/2.0/",
      "source": "https://www.flickr.com/photos/55191813@N03/28608585192"
    }
  },
  "rj-h3": {
    "id": "rj-h3",
    "widths": [
      1280,
      1920
    ],
    "aspect": 1.85,
    "lqip": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAABwAwCdASoUAAsAPxFysVAsJqSisAgBgCIJZwAAP4SsXyTaDwAA/tC3utHc9lW60ZOq2hSluUqdV83cYJ6fv5qBbEkAAA==",
    "mobile": {
      "widths": [
        480,
        760
      ],
      "aspect": 0.75,
      "lqip": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAACQBACdASoUABsAPxF2rFCsJ6QisBgMAYAiCWcAyrQQaPkvmxxc0DSHw8qDkoAA8Y9PKqEp6i6eRkYd1lBpFQ+KkLuhDy99NBjJNLLI+w919EXTmcrym40gh/tXQOAAAAA="
    },
    "credit": {
      "creator": "Well-Bred Kannan (WBK Photography)",
      "license": "BY-NC-ND 2.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-nc-nd/2.0/",
      "source": "https://www.flickr.com/photos/55191813@N03/28636423051"
    }
  },
  "rj-h4": {
    "id": "rj-h4",
    "widths": [
      1280,
      1920
    ],
    "aspect": 1.85,
    "lqip": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADQAwCdASoUAAsAPxF2slEsJySisAgBgCIJYgCdABaGhkvVJt2StnAA/AtE0li/H+fV1IvjtYNzIe9oPC773C1CUuC/DrmVc2+TaX5n1Vo2AA==",
    "mobile": {
      "widths": [
        480,
        760,
        1000
      ],
      "aspect": 0.75,
      "lqip": "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAADQBACdASoUABsAPxF0sFAsJqSisAgBgCIJYwCw7Aw2z08mcn/cQtny2c1qDeVuAAD+JlgyI/bkyJWjU5JpTTwHYPLZdYP3Edvb4dnECO/7YsrCgA+9Xn5MfMgaeayVHCAdj1DVZgPzDjGxumMm8ajGGVL7d133CsmMc+LGxT6nE4PbnzYofXgA"
    },
    "credit": {
      "creator": "Karl Grenet",
      "license": "BY-NC-ND 2.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-nc-nd/2.0/",
      "source": "https://www.flickr.com/photos/128166960@N08/15888231121"
    }
  },
  "rj-h5": {
    "id": "rj-h5",
    "widths": [
      1280,
      1920
    ],
    "aspect": 1.85,
    "lqip": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAACQAwCdASoUAAsAPxF2sVCsJySisAgBgCIJZwAAWm/fJuNyDj4AAP7MUXt1Ld6vllU72QYpcfG9r6eUWbKY+3W5AAA=",
    "mobile": {
      "widths": [
        480,
        760,
        1000
      ],
      "aspect": 0.75,
      "lqip": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAAAwBQCdASoUABsAPxFwslAsJiSisBgMAYAiCWcAw3AQqqRkQI2sJBmhxL/urenF/FCAAAD+zYx4JkqOIoW7lbcGVhXWgABAV6YpBur+NYM91gzQs8CBuyFlsVxLZmqvtuqt9jth8AA="
    },
    "credit": {
      "creator": "llinke",
      "license": "BY-NC-SA 2.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-nc-sa/2.0/",
      "source": "https://www.flickr.com/photos/51384832@N00/2673225489"
    }
  },
  "rj-h6": {
    "id": "rj-h6",
    "widths": [
      1280,
      1920
    ],
    "aspect": 1.85,
    "lqip": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAACwAwCdASoUAAsAPxFysFAsJqSisAgBgCIJYgCdMoABlNv2WvYv0AD8T0hciQCPmptXVDaExQKSyNerT7dKdhinxLNMltV+wMASwO88bL5CsBOAAAA=",
    "mobile": {
      "widths": [
        480,
        760,
        1000
      ],
      "aspect": 0.75,
      "lqip": "data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAAAQBQCdASoUABsAPxFytFMsJiUisBgIAYAiCWIAqPQQ32v5tvXea7F69X85ZTIb0ApgAP38GhhiVd8QDtDD0FObOy0fNBAIlO7Dns+ZF6j08dCOpmGOMqwgQmSvDaEsBMG0K+tWPa99hCPJpu5dmU5HGxbnNRFygN56XVyc63Mw4+31+cwpL55NFjqHyAAA"
    },
    "credit": {
      "creator": "Well-Bred Kannan (WBK Photography)",
      "license": "BY-NC-ND 2.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-nc-nd/2.0/",
      "source": "https://www.flickr.com/photos/55191813@N03/28609155062"
    }
  },
  "rj-h7": {
    "id": "rj-h7",
    "widths": [
      1280,
      1920
    ],
    "aspect": 1.85,
    "lqip": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADQAwCdASoUAAsAPxFwsFAsJiSisAgBgCIJZgCdAB6E9sFrQW0pkIAA/jwrJ/K+xLTtVn1ON+Qs/rWa/RN+0bQsH17+YGkyxTJshxIGjIO48RFdDqukAA==",
    "mobile": {
      "widths": [
        480,
        760,
        1000
      ],
      "aspect": 0.75,
      "lqip": "data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAACQBACdASoUABsAPxFysFAsJqSisAgBgCIJZgCxHy/DTpe8dQYotARbE2x5S8YA/qZGV8ukYN0Nw8xbV2Jm913JyZMMnQ9z4Tqnt/qh+RcYksFq9NOBbFmC4giqmafDcryKk4ndokGTXxhtWfbsU2n5x0JtLJnK+r/R5gAA"
    },
    "credit": {
      "creator": "orange tuesday",
      "license": "BY-NC 2.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-nc/2.0/",
      "source": "https://www.flickr.com/photos/63138333@N00/2116688453"
    }
  },
  "rj-w1": {
    "id": "rj-w1",
    "widths": [
      600,
      900
    ],
    "aspect": 0.8,
    "lqip": "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAABwBACdASoUABkAPxF0s1EsJqSiqA1RgCIJZACuHA9L/2m5GnxHktBZsLW8AAD6Cm64ikdHvfJ4t93m4dax9KmXx2lpEPq8jsIbsN0QrIR8pXM3c2fFQw5RmxlVgluUdVkIlnKuJU5xa8ug3QgfgsbvgAA=",
    "mobile": null,
    "credit": {
      "creator": "rahuldlucca",
      "license": "BY 2.0",
      "licenseUrl": "https://creativecommons.org/licenses/by/2.0/",
      "source": "https://www.flickr.com/photos/8213176@N03/2245306787"
    }
  },
  "rj-w2": {
    "id": "rj-w2",
    "widths": [
      720,
      1100
    ],
    "aspect": 1.5,
    "lqip": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAACQAwCdASoUAA0APxFyslCsJqSisAgBgCIJQBOgAtvNS7Fac80AAPtc2O/RqbabJlHP0DJMyHF+6vwbfgHgurGPNYX9YmZeAAA=",
    "mobile": null,
    "credit": {
      "creator": "SimpleSkye",
      "license": "BY 2.0",
      "licenseUrl": "https://creativecommons.org/licenses/by/2.0/",
      "source": "https://www.flickr.com/photos/44452897@N05/32428668070"
    }
  },
  "rj-w3": {
    "id": "rj-w3",
    "widths": [
      720,
      1100
    ],
    "aspect": 1.5,
    "lqip": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAACQAwCdASoUAA0APxFysVAsJqSisAgBgCIJQAAGlN1sZBfbB0gAANs0lDVEAkDkaIEpgt//tesNIJy3LgOtFEy+2+3xCMs95ybQAA==",
    "mobile": null,
    "credit": {
      "creator": "Ivan Radic",
      "license": "BY 2.0",
      "licenseUrl": "https://creativecommons.org/licenses/by/2.0/",
      "source": "https://www.flickr.com/photos/26344495@N05/50439338427"
    }
  },
  "rj-w4": {
    "id": "rj-w4",
    "widths": [
      720,
      1100
    ],
    "aspect": 1.5,
    "lqip": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAAAQBACdASoUAA0APxFysVAsJqSisAgBgCIJQBOmUGSxh+6DpdAAv1V84ADpQzXfbTFqdUwofOsIYTIWNBjpyUzKBiRErtP/Lq6zgoUuuLgAAA==",
    "mobile": null,
    "credit": {
      "creator": "lars hammar",
      "license": "BY-NC-SA 2.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-nc-sa/2.0/",
      "source": "https://www.flickr.com/photos/7603557@N08/1150483779"
    }
  },
  "rj-w5": {
    "id": "rj-w5",
    "widths": [
      900,
      1400
    ],
    "aspect": 1.85,
    "lqip": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAACwAwCdASoUAAsAPxF0slCsJqSisAgBgCIJZwDImBVVN4yUf6P8YAD+hql3F5LlxxGTZpFDkt47vXsBVyYnNHJcLWGhwekAAAA=",
    "mobile": null,
    "credit": {
      "creator": "Well-Bred Kannan (WBK Photography)",
      "license": "BY-NC-ND 2.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-nc-nd/2.0/",
      "source": "https://www.flickr.com/photos/55191813@N03/28608592872"
    }
  },
  "rj-w6": {
    "id": "rj-w6",
    "widths": [
      600,
      900,
      1200
    ],
    "aspect": 0.8,
    "lqip": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAAAwBACdASoUABkAPxFur1EsJiQisBgMAYAiCWMAyJgn/xXHEh0JQzJPFAAAwrThWgaZbYF5ZGIsVeBJWN0VVV92mP6b/uuwSIsyGqkvoumvEeXx/mfPiI1ugAA=",
    "mobile": null,
    "credit": {
      "creator": "HousingRevolution.org",
      "license": "BY-NC-SA 2.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-nc-sa/2.0/",
      "source": "https://www.flickr.com/photos/64737793@N04/5923112498"
    }
  },
  "rj-o1": {
    "id": "rj-o1",
    "widths": [
      480,
      720,
      960
    ],
    "aspect": 1,
    "lqip": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAABwBACdASoUABQAPw1srlAsJaQit/VYAYAhiWcAwNwQ7jDKLf3cPC6/S7k/gAD+7UNRVla7nhngm+8WMer49LXZcElx0gW9or9Vh3U44Sja5Yux4ZenBOhIr+3kyxCHi5JOAAAA",
    "mobile": null,
    "credit": {
      "creator": "ninahale",
      "license": "BY 2.0",
      "licenseUrl": "https://creativecommons.org/licenses/by/2.0/",
      "source": "https://www.flickr.com/photos/94693506@N00/377916126"
    }
  },
  "rj-o2": {
    "id": "rj-o2",
    "widths": [
      480,
      720,
      960
    ],
    "aspect": 1,
    "lqip": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAABQBACdASoUABQAPwVwrFArpqQit/VYAXAgiWcAzFgQ4ICRkcPxWEICEgPAAP549bWsbHe1/zbo/ND9mfuRr/EnSuDxRHxI/i8uBOIgSBmlZIAA",
    "mobile": null,
    "credit": {
      "creator": "mckaysavage",
      "license": "BY 2.0",
      "licenseUrl": "https://creativecommons.org/licenses/by/2.0/",
      "source": "https://www.flickr.com/photos/56796376@N00/3016006648"
    }
  },
  "rj-o3": {
    "id": "rj-o3",
    "widths": [
      480,
      720,
      960
    ],
    "aspect": 1,
    "lqip": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAACQBACdASoUABQAPxF2slGsJySiqA1RgCIJZwC/OA7viqHDYWznUiNkiTfI3AAA/TXM+DUheCrZU4wmep6FaON1xoKUKLh4r0Nyd+5eAFlbt/6A64UvVHXpZmQAAA==",
    "mobile": null,
    "credit": {
      "creator": "whatleydude",
      "license": "BY 2.0",
      "licenseUrl": "https://creativecommons.org/licenses/by/2.0/",
      "source": "https://www.flickr.com/photos/85318305@N00/4982663507"
    }
  },
  "rj-o4": {
    "id": "rj-o4",
    "widths": [
      480,
      720,
      960
    ],
    "aspect": 1,
    "lqip": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAADwBACdASoUABQAPxFss1AsJaUisBgMAYAiCWUAxnwQ8Q5EwY729t889iddckqDjAAAy0fYcwF9kQTVMslfejOYlUkOUBq/Kiiil3+5UqYYZchoUCMm0ALgZJTyU3JfAAA=",
    "mobile": null,
    "credit": {
      "creator": "el cajon yacht club",
      "license": "BY 2.0",
      "licenseUrl": "https://creativecommons.org/licenses/by/2.0/",
      "source": "https://www.flickr.com/photos/60944636@N00/51402349573"
    }
  },
  "rj-o5": {
    "id": "rj-o5",
    "widths": [
      480,
      720,
      960
    ],
    "aspect": 1,
    "lqip": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAACQBACdASoUABQAPxFyr1CsJqQisBgMAYAiCWYAt7gQ6Z2Rv7pNMi+MjwERagAA/unyrW74ugF3lkzI7XEGcKFiPIHrf0Zt6/Ely1k5zj79Cm9pR3J3z9CzCD0O+7h3vRqR2+JUcUAAAA==",
    "mobile": null,
    "credit": {
      "creator": "Ahmad Faiz Mustafa",
      "license": "BY-SA 3.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
      "source": "https://commons.wikimedia.org/w/index.php?curid=28013957"
    }
  },
  "rj-dream": {
    "id": "rj-dream",
    "widths": [
      1280,
      1920
    ],
    "aspect": 1.7778,
    "lqip": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAAAQBACdASoUAAsAPxFysVCsJqSisAgBgCIJbACdMoAC+Z0ssTEHlrzl0AD+31KftpjdqFSprWZKmScNWhwg0lLHU/Ysd67vrubjGNd43k/igIZwyzwQ75YaAAA=",
    "mobile": {
      "widths": [
        480,
        760
      ],
      "aspect": 0.75,
      "lqip": "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAAAwBQCdASoUABsAPxF6slQsJ6QjKAqpgCIJaACC8TgAOjPLw50yWwCSX52yoJrDN4iwyAD+6m91scuVHLPYzkU6dhLlk//UvhQiR6jtO32SJ199HVnGYQiIeuqd4uLd9Y4eLfVXiMia4ur68tKIwAAA"
    },
    "credit": {
      "creator": "rahuldlucca",
      "license": "BY 2.0",
      "licenseUrl": "https://creativecommons.org/licenses/by/2.0/",
      "source": "https://www.flickr.com/photos/8213176@N03/2245821764"
    }
  }
} satisfies Record<string, Frame>

export type FrameId = keyof typeof FRAMES
