// AUTO-GENERATED by tools/fetch-audio.mjs — do not edit by hand.
export type Sound = {
  slug: string
  src: string
  seconds: number
  bytes: number
  credit: { creator: string; license: string; licenseUrl: string; source: string; title: string }
}

export const SOUNDS = {
  "before-light": {
    "slug": "before-light",
    "src": "/sounds/before-light.mp3",
    "seconds": 25,
    "bytes": 570700,
    "credit": {
      "creator": "kevp888",
      "license": "BY 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
      "source": "https://freesound.org/people/kevp888/sounds/578754",
      "title": "BR_049_India_GangesRiver.mp3"
    }
  },
  "the-site": {
    "slug": "the-site",
    "src": "/sounds/the-site.mp3",
    "seconds": 25,
    "bytes": 466176,
    "credit": {
      "creator": "peridactyloptrix",
      "license": "CC0 1.0",
      "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
      "source": "https://freesound.org/people/peridactyloptrix/sounds/221922",
      "title": "Building site interior ambience"
    }
  },
  "the-road": {
    "slug": "the-road",
    "src": "/sounds/the-road.mp3",
    "seconds": 25,
    "bytes": 590060,
    "credit": {
      "creator": "kevp888",
      "license": "BY 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
      "source": "https://freesound.org/people/kevp888/sounds/578755",
      "title": "BR_056_India_Street.mp3"
    }
  },
  "after-dark": {
    "slug": "after-dark",
    "src": "/sounds/after-dark.mp3",
    "seconds": 25,
    "bytes": 557568,
    "credit": {
      "creator": "Abinash87",
      "license": "CC0 1.0",
      "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
      "source": "https://freesound.org/people/Abinash87/sounds/130412",
      "title": "Night cricket ambience.wav"
    }
  }
} satisfies Record<string, Sound>

export type SoundId = keyof typeof SOUNDS
